name: Build and Publish Plugin (Dev)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17 with Gradle Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shadowJar
        run: ./gradlew clean shadowJar

      - name: Extract Version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep "projectVersion=" gradle.properties | cut -d'=' -f2 | tr -d '\r')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Rename JAR to include Build Number
        run: |
          for file in build/libs/*.jar; do
            mv "$file" "${file%.jar}-dev.${{ github.run_number }}.jar"
          done

      - name: Publish Dev Build to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: '3F4nxJLs'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: '1411557'
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          name: SneakJump ${{ env.version }} (Dev ${{ github.run_number }})
          
          version: ${{ env.version }}-alpha.${{ github.run_number }}
          version-type: alpha
          
          loaders: bukkit, paper, purpur, spigot
          game-versions: ">=1.8 <=1.21.11"
          
          files: build/libs/*.jar

      - name: Delete old GitHub dev release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete dev-build --cleanup-tag -y || true

      - name: Create Rolling Dev Release in GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          tag_name: dev-latest
          name: 🚧 Development Build (Latest)
          generate_release_notes: true
          prerelease: true
          files: build/libs/*.jar
